BASE_DIR = './'

workdir: BASE_DIR

SAMPLES, = glob_wildcards(BASE_DIR + "{sample}_1.fq.gz")

rule all:
    input: expand("paired/{sample}_1.qc.fq.gz", sample=SAMPLES), expand("unpaired/{sample}_1.unp.fq.gz", sample=SAMPLES), expand("paired/{sample}_2.qc.fq.gz", sample=SAMPLES), expand("unpaired/{sample}_2.unp.fq.gz", sample=SAMPLES)

rule qc:
    input: "{sample}_1.fq.gz", "{sample}_2.fq.gz"
    output: "paired/{sample}_1.qc.fq.gz", "unpaired/{sample}_1.unp.fq.gz", "paired/{sample}_2.qc.fq.gz", "unpaired/{sample}_2.unp.fq.gz"
    shell: """
        java -jar ~/Downloads/Trimmomatic/dist/jar/trimmomatic-0.40-rc1.jar PE -threads 20 {input} {output} ILLUMINACLIP:bacode.fa:2:30:10 LEADING:3 TRAILING:3 MINLEN:36
    """